# Data Science Accelerator Capstone Project

### Daniel Coles

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('data/Gravity_V202211.csv')

/tmp/ipykernel_183184/1413982463.py:1: DtypeWarning: Columns (0: empire) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/Gravity_V202211.csv')

In [8]:
print(f"No of Columns: {len(df.columns)}")
print(f"No of Rows: {len(df)}")
df.head()

No of Columns: 87
No of Rows: 4699296

,year,country_id_o,country_id_d,iso3_o,iso3_d,iso3num_o,iso3num_d,country_exists_o,country_exists_d,gmt_offset_2020_o,...,entry_time_o,entry_time_d,entry_tp_o,entry_tp_d,tradeflow_comtrade_o,tradeflow_comtrade_d,tradeflow_baci,manuf_tradeflow_baci,tradeflow_imf_o,tradeflow_imf_d
0,1948,ABW,ABW,ABW,ABW,533.0,533.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1949,ABW,ABW,ABW,ABW,533.0,533.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1950,ABW,ABW,ABW,ABW,533.0,533.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1951,ABW,ABW,ABW,ABW,533.0,533.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1952,ABW,ABW,ABW,ABW,533.0,533.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.describe()

,year,iso3num_o,iso3num_d,country_exists_o,country_exists_d,gmt_offset_2020_o,gmt_offset_2020_d,distw_harmonic,distw_arithmetic,distw_harmonic_jh,...,entry_time_o,entry_time_d,entry_tp_o,entry_tp_d,tradeflow_comtrade_o,tradeflow_comtrade_d,tradeflow_baci,manuf_tradeflow_baci,tradeflow_imf_o,tradeflow_imf_d
count,4.699296e+06,4.680648e+06,4.680648e+06,4.699296e+06,4.699296e+06,4.124232e+06,4.124232e+06,3.627844e+06,3.627844e+06,735210.000000,...,769608.000000,769608.000000,769608.000000,769608.000000,8.455410e+05,9.658380e+05,6.948280e+05,6.948280e+05,9.135640e+05,1.001734e+06
mean,1.984500e+03,4.381076e+02,4.381076e+02,8.776276e-01,8.776276e-01,1.553984e+00,1.553984e+00,8.602488e+03,8.616183e+03,7816.026907,...,32.679339,32.679339,40.833235,40.833235,4.060194e+05,3.696366e+05,4.445421e+05,3.665871e+05,3.899912e+05,3.622398e+05
std,2.136001e+01,2.507368e+02,2.507368e+02,3.277154e-01,3.277154e-01,5.013345e+00,5.013345e+00,4.744739e+03,4.736602e+03,4504.277820,...,47.504278,47.504278,49.292653,49.292653,4.558918e+06,4.259624e+06,4.678032e+06,4.204625e+06,4.442396e+06,4.219091e+06
min,1.948000e+03,4.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,-1.100000e+01,-1.100000e+01,0.000000e+00,0.000000e+00,1.000000,...,0.500000,0.500000,1.500000,1.500000,1.000000e-03,1.000000e-03,1.000000e-03,0.000000e+00,1.000000e-03,1.000000e-03
25%,1.966000e+03,2.220000e+02,2.220000e+02,1.000000e+00,1.000000e+00,-3.000000e+00,-3.000000e+00,4.845000e+03,4.855000e+03,4302.000000,...,10.000000,10.000000,16.300000,16.300000,1.501260e+02,5.570600e+01,6.392825e+01,3.894200e+01,1.807190e+02,1.200000e+02
50%,1.984500e+03,4.400000e+02,4.400000e+02,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,8.223000e+03,8.231000e+03,7404.000000,...,19.000000,19.000000,28.000000,28.000000,2.533419e+03,1.371986e+03,1.613026e+03,1.007671e+03,2.604472e+03,2.168750e+03
75%,2.003000e+03,6.540000e+02,6.540000e+02,1.000000e+00,1.000000e+00,4.000000e+00,4.000000e+00,1.218100e+04,1.218600e+04,10979.000000,...,39.000000,39.000000,49.000000,49.000000,3.269088e+04,2.381548e+04,3.154437e+04,2.148002e+04,3.115600e+04,2.752173e+04
max,2.021000e+03,8.940000e+02,8.940000e+02,1.000000e+00,1.000000e+00,1.300000e+01,1.300000e+01,1.990400e+04,1.990400e+04,19750.000000,...,697.500000,697.500000,710.500000,710.500000,4.797001e+08,5.632004e+08,5.009282e+08,4.981595e+08,4.806887e+08,5.395034e+08

In [16]:
df[df['year'] == 2000]['iso3num_o']

52         533.0
126        533.0
200        533.0
274        533.0
348        533.0
           ...
4698978    716.0
4699052    716.0
4699126    716.0
4699200    716.0
4699274    716.0
Name: iso3num_o, Length: 63504, dtype: float64